### ISSUE TITLE
not working under macOS

### ISSUE THREAD

**Issue by paxcoder** [chrys87/fenrir#62]
Hi.
some people told me that this will work under macOS, but installation fails, because the script is trying to install it in a location that is locked, due to security.

**Comment by stormdragon2976** [comment]
You can run it without installing to /usr/bin, right from the git
directory. I don't know all that much about the Mac, but I suspect only
the pty mode will work, and you may need to change the keyboard layout
to pty2. I am not sure what, if any other changes would need to be made.

**Comment by chrys87** [comment]
@stormdragon2976 is right, you can start fenrir just from git without need of any installation. but you need to install the required  dependencies. 
the most important one for you seems to be: 

- pyte (pythton modul for terminal emulation)
- sox (for sound output)
- espeak-ng (for basic TTS)
- pyenchant (for spellchecking)

the you can just go to your local cloned git location 
`<gitroot>/src/fenrir -e`

the parameter -e uses the terminal emulation mode. so it reads the information from stin / stout and sterr and presents it to you.

**Comment by Martin1088** [comment]
Hi

I have tried it this way.
And got:
fernir -e
Not to work:

(myenv) ➜  src git:(master) ✗ ./fenrir -e
Traceback (most recent call last):
  File "/Users/m049k/Projects/screenreader/fenrir/src/./fenrir", line 21, in <module>
    main()
    ^^^^^^
  File "/Users/m049k/Projects/screenreader/fenrir/src/./fenrir", line 16, in main
    app = fenrirManager.fenrirManager()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

But ./fenrir -s ../config/settings/settings-pty.conf
The fenrir starts speaking but:
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/m049k/Projects/screenreader/fenrir/src/fenrirscreenreader/core/processManager.py", line 92, in simpleEventWorkerThread
    self.env['runtime']['eventManager'].putToEventQueue(event, Data)
  File "/Users/m049k/Projects/screenreader/fenrir/src/fenrirscreenreader/core/eventManager.py", line 92, in putToEventQueue
    if self.getEventQueueSize() > 50:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m049k/Projects/screenreader/fenrir/src/fenrirscreenreader/core/eventManager.py", line 86, in getEventQueueSize
    return self._eventQueue.qsize()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError
